[phases.setup]
nixPkgs = [
  "php82", 
  "composer", 
  "php82Extensions.pdo_mysql", 
  "php82Extensions.mbstring", 
  "php82Extensions.zip"
]

[phases.build]
cmds = [
  "composer install",
  "php artisan config:cache",
  "php artisan migrate --force"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
